services:
  backend:
    build: .
    container_name: hacksquad-container
    env_file:
      - .env
    ports:
      - "8000:8080"
    environment:
      - PORT=8080
      - GOOGLE_APPLICATION_CREDENTIALS=${GOOGLE_APPLICATION_CREDENTIALS}
    volumes:
      - .:/app
      - ./credentials.json:/app/credentials.json

    command: >
      gunicorn --bind :8080 --workers 1 --worker-class uvicorn.workers.UvicornWorker --threads 8 app.main:app