global:
  scrape_interval: 15s
  evaluation_interval: 120s

scrape_configs:
  - job_name: 'hacksquad_app'
    static_configs:
      - targets: ['hacksquad:8080']   # Si tu exposes /metrics dans FastAPI

  - job_name: 'mysql'
    static_configs:
      - targets: ['mysqld-exporter:9104']

  - job_name: prometheus
    static_configs:
      - targets: ['localhost:9091']
    metrics_path: '/metrics'
